name: Deploy

on:
  push:
    branches:
      - master

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
    
    - name: Assets build & deploy
      env:
        HOST_NAME: ${{ secrets.HOST_NAME }}
        REMOTE_LOCATION: ${{ secrets.REMOTE_LOCATION }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      run: |
        # echo "INFO:: Installing bundler"
        # gem install bundler
        # echo "INFO:: Building..."
        # bundle install --jobs=4
        # bundle exec jekyll build
        echo "INFO:: Create private key"
        echo "$PRIVATE_KEY" > ./id_rsa
        sudo chmod 600 ./id_rsa
        cat ./id_rsa
        echo "INFO:: Synching with remote $HOST_NAME"
        ssh -i ./id_rsa $HOST_NAME
        # rsync -raL --delete -P -e "ssh -i ./id_rsa" ./_site/ $HOST_NAME:$REMOTE_LOCATION
        echo "INFO:: Done!"