name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - '_posts/**'
      - 'assets/**'
      - '_layouts/**'
      - '_includes/**'
      - '**.md'
  workflow_dispatch:

concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: live

    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.3'
    
    # Restore the vendor/bundle folder
    # from cache
    - name: Cache ruby gems
      uses: actions/cache@v4
      env:
        cache-name: ruby-gems
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Gemfile.lock') }}

    - name: Install Depdencies
      run: |
        gem install bundler
        bundle config set path 'vendor/bundle'
        bundle install --jobs=4

    - name: Build
      run: |
        bundle exec jekyll build

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@164a3e861eade8146ae8bd738d66b107e70ad6cf
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        ARGS: "-raL --delete"
        SOURCE: "_site/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_DEPLOY_PATH }}
        REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
