name: Deploy

on:
  push:
    branches:
      - master

jobs:

  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
    
    - name: Build Assets
      run: |
        echo "INFO:: Installing bundler"
        gem install bundler
        echo "INFO:: Building..."
        bundle install --jobs=4
        bundle exec jekyll build
        npm ci

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.1
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        ARGS: "-raL --delete"
        SOURCE: "_site/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_LOCATION }}